<?xml version="1.0" encoding="utf-8"?><Database Name="CabData" Class="CabDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=CabData;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CabDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HomePhone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ConfirmationToken" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SubscribeNewsletter" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ForgotPasswordToken" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Discount" Member="Discounts">
    <Type Name="Discount">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Percent]" Member="Percent" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="JobToken" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClientToken" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ValidTill" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GeneratedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsExpired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Driver" Member="Drivers">
    <Type Name="Driver">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="JobStatus" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AccountStatus" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DutyHours" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StartingDate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EndingDate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastLocation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DriverNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AvailableTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Town" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Shift" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InsuranceExpires" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MotExpires" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RoadTaxExpires" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BadgeNumberExpires" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PersonalPCOExpires" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VehiclePcoExpires" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NINumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LicenseNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BadgeNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VehicleType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VehicleMake" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VehicleModel" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VehicleRegistrationNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VehicleOwner" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VehicleColor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VehicleImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DriverPhoto" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AccountNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SortCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CardPercent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CashPercent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CallSignAbbr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CallSignNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DocsToken" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DispatchJob" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VehicleOwnerName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VehicleOwnerAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CarStart" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CarEnd" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VehicleKeeperName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VehicleKeeperAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AirportWebComission" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VehicleKeeperPostCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VehicleOwnerPostCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DriverTarget" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DriverIncome" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MotStarts" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NextOfKin" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EmergencyNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CarBadgeNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fare" Member="Fares">
    <Type Name="Fare">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[From]" Member="From" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[To]" Member="To" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Vehicles" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CashFares" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SiteToken" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CardFares" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DriverFares" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Feedback" Member="Feedbacks">
    <Type Name="Feedback">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBooking" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FeedbackDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsFirstBooking" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ScoreForUs" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ScoreForCustomerService" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ScoreForJourney" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ScoreForOnlineBooking" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DefineOurService" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="BookUsAgain" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Job" Member="Jobs">
    <Type Name="Job">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PickFrom" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DropTo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PickupTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DriverToken" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClientToken" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PaidAs" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Stops" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Luggage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfPassengers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VehicleToken" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ChildSeats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BabySeats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CellNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="POBTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CompletedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalInfo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Fare" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HandLag" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LandLine" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="JourneyType" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ReturnTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ConfirmationToken" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PassengerName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PassengerCell" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BottleOfWater" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Newspaper" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Drink" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="JobNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SiteToken" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="BookingTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BookingFrom" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MinicabOffice" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CardTransactionCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BusinessAccountHolder" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Location" Member="Locations">
    <Type Name="Location">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PostCode" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DoorNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MinicabOffice" Member="MinicabOffices">
    <Type Name="MinicabOffice">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LicenceNumber" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="BookingFrom" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Notification" Member="Notifications">
    <Type Name="Notification">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Sender" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Receiver" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SentAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReceivedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="JobToken" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Site" Member="Sites">
    <Type Name="Site">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Logo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EmailSMTP" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EmailPassword" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EmailPort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AirportNames" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AirportCharges" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CardOff" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CashOff" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StartingHour" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EndingHour" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PrebookBeforeHours" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="BookingEmail" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AccountEmail" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DispatchEmail" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Vehicle" Member="Vehicles">
    <Type Name="Vehicle">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SiteToken" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaxPassengers" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxLuggages" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxBabySeats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxChildSeats" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxHandLag" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeetAndGreet" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PricePerMile" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MinimumPrice" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MilesIncluded" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FareForMilesIncluded" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PriceForOneMinuteWait" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PriceForLocalViaStop" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReturnDiscount" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WaitAndReturnDiscount" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>